name: Deploy React Vite App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # --- REMOVE THESE TWO LINES FROM HERE ---
          # cache: 'pnpm'
          # cache-dependency-path: pnpm-lock.yaml

      # This step will now correctly install pnpm and handle its caching
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # Or a specific version like '8.15.5', or leave blank for latest stable
          run_install: false # We will run 'pnpm install --frozen-lockfile' ourselves next
          # --- ADD pnpm caching options here ---
          # pnpm/action-setup handles its own caching for the pnpm store and dependencies
          # by default when it installs pnpm, it links to the cache directory.
          # You usually don't need to explicitly configure `cache` here for pnpm/action-setup.
          # However, if you wanted to pass a custom cache key, you'd do it here.

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Copy index.html to 404.html for SPA routing
        run: cp dist/index.html dist/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
