name: Deploy React Vite App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Or your preferred Node.js version
          cache: "pnpm" # <--- CHANGE THIS to 'pnpm'
          cache-dependency-path: pnpm-lock.yaml # <--- ADD THIS LINE

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # <--- CHANGE THIS to pnpm command

      - name: Build project
        run: pnpm run build # <--- Optional: If your build script is just 'build', this works. If it's a different script, adjust accordingly.

      - name: Copy index.html to 404.html for SPA routing
        run: cp dist/index.html dist/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
